### ISSUE TITLE
Add more config?

### ISSUE THREAD

**Issue by dzek69** [xthezealot/npmprune#1]
Hey,

Your project seems nice and... familar. Maybe there are more project like this, but I've only used one. Yarn. `yarn` used to have something like this: https://classic.yarnpkg.com/lang/en/docs/cli/autoclean/

...and it was cool and useful, but your project is very fragile the same resason autoclean was fragile and therefore was not widely used and got removed: it can remove files that are actually needed for various reasons. 

yarn never solved that, so people using autoclean were actually missing a lot of opportunities to clean up. On the other hand - some people, me including were using it in a very aggressive mode and that was REALLY saving a lot of disk space. But I had to manually add so many exclusions to the list of files I want to remove I actually stopped using this feature.

But I see I digress a little bit.

The point is:
- configurability is very much needed
- if you want your project to success it requires a lot of thinking how to make it squize the most of the possible disk space but allow to easy fix any mistakes

Thanks & good luck,
Jacek

**Comment by xthezealot** [comment]
Hi Jacek,

You're right, there are indeed other tools similar to this one, but many are no longer maintained.  
This situation led me to write a more flexible approach that can be swiftly integrated into Docker image creation. 

The aim of this script is to maintain simplicity and generality, rather than being extremely aggressive.  
I specifically wanted to make a simple "integrate and forget" solution (like Prettier does for code formatting). 

For example, this script already saves 250 MB on a project like Strapi without breaking it.  
I think we have a good balance between space saving and safety.

Still, I appreciate your feedback, thank you!
